version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    working_dir: /app
    expose:
      - 8000
    env_file:
      - backend/.env

  frontend:
    image: node:18.19.0
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    expose:
      - 5173
    env_file:
      - app/.env
    depends_on:
      - backend